### ISSUE TITLE
Upgrade to latest version?

### ISSUE THREAD

**Issue by BrianVallelunga** [tg123/Docker-AzureStorageEmulator#1]
Any chance you could upgrade the emulator version to the latest version? I believe this is the newest direct download URL: https://download.visualstudio.microsoft.com/download/pr/12905117/3bd7826884edd5468c8819a04e871dfe/MicrosoftAzureStorageEmulator.msi

**Comment by tg123** [comment]
Sure You can send a PR, or I will change and test myself.
