### ISSUE TITLE
Container exits right away with error code 1

### ISSUE THREAD

**Issue by RobLSDev** [tg123/Docker-AzureStorageEmulator#3]
I attempted to run this image locally and haven't had any luck.  It appears to be an issue with the command line to start nginx.

`PS C:\WINDOWS> docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 microsoft/azure-storage-emulator
Windows Azure Storage Emulator 5.7.0.0 command line tool
The storage emulator was successfully started.
nginx: [emerg] unexpected end of parameter, expecting ";" in command line
`
`PS C:\WINDOWS> docker ps -a
CONTAINER ID        IMAGE                              COMMAND                   CREATED              STATUS                          PORTS               NAMES
ce1a5cb3b608        microsoft/azure-storage-emulator   "cmd /S /C C:\\entryp…"   About a minute ago   Exited (1) About a minute ago                       gallant_lalande
`

**Comment by tg123** [comment]
could you please try  `farmer1992/azure-storage-emulator`

for MS repo, we are moving to a new project https://github.com/Azure/Azurite
thus, the old .net version was freeze

**Comment by tg123** [comment]
reopen if you still cannot use the image
