### ISSUE TITLE
Container exists with error code with nginx error

### ISSUE THREAD

**Issue by preetriti1** [tg123/Docker-AzureStorageEmulator#5]
Hi,

I am running the following command to run storage emulator in a windows container.
docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 farmer1992/azure-storage-emulator:latest

And i get the following error - 
Windows Azure Storage Emulator 5.9.0.0 command line tool
The storage emulator was successfully started.
nginx: [emerg] unexpected end of parameter, expecting ";" in command line

It seems the image does not have the fix as proposed in another thread. Could you please upload the latest image with the fix?

Thanks.

**Comment by tg123** [comment]
please see #3

**Comment by tg123** [comment]
do you mean latest
I will test latest tag again

I remember I fixed it on 5.9

**Comment by preetriti1** [comment]
Yes, i was using the latest tag.. which one should i be using to pull the image.

**Comment by tg123** [comment]
Can I know your docker version and windows version

Cannot repro

**Comment by tg123** [comment]
fixed by #4
