### ISSUE TITLE
Update microsoft/azure-storage-emulator just once more to fix the nginx error?

### ISSUE THREAD

**Issue by fschmied** [tg123/Docker-AzureStorageEmulator#6]
I know that Microsoft has moved towards azurite, but for those of us who need to use a Windows container (e.g., in a docker-compose setup with other Windows containers), it would be great if you could update `microsoft/azure-storage-emulator` (and synchronize it with `farmer1992/azure-storage-emulator`) just one more time  to fix #3.

Why not just use `farmer1992/azure-storage-emulator` instead?
* Because that's a private repository and we feel much more comfortable with using images from an official one.
* Because whenever someone searches for the storage emulator on Github, they'll try the official one first and then go on a search for why it doesn't work.
* Because it's just strange that there is an official image that's broken.

(If this is the wrong place to ask for this, please direct me to the right one of the different Azure Github projects where I should ask; thank you!)

**Comment by tg123** [comment]
sorry I cannot update it anymore :(
maybe you can try LCOW
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

Aslo, Azurite is node based. it is easy to create a Windows based Azurite

**Comment by pbering** [comment]
I use this on for Azurite on Windows: 

```
FROM stefanscherer/node-windows:10.16.3-nanoserver-1809

RUN npm install -g azurite@3.4.0 2>&1

# blob storage port
EXPOSE 10000

# queue storage port
EXPOSE 10001

VOLUME [ "C:/data" ]

CMD ["C:/nodejs/azurite.cmd", "--location", "C:/data", "--blobHost", "0.0.0.0","--queueHost", "0.0.0.0"]
```

**Comment by fschmied** [comment]
Okay, thanks everyone for the responses.
